name: Build and Release PDF

on:
  push:
    branches:
      - main
  create:
    tags:
      - v*

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Build Assets
        run: npm run build

      - name: Build PDF
        run: npm run print

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "dist/assets/pdf/EmadMalekpour-SeniorDeveloper_EN.pdf"
          token: ${{ secrets.PAT_TOKEN }}
          draft: false
          prerelease: false
          files_glob: '*'
          tag: v${{ steps.get_version.outputs.version }}

      - name: Upload PDF to release
        uses: actions/upload-artifact@v3
        with:
          name: EmadMalekpour-SeniorDeveloper_EN.pdf
          path: dist/assets/pdf/EmadMalekpour-SeniorDeveloper_EN.pdf
